### ISSUE TITLE
Images

### ISSUE THREAD

**Issue by drjwbaker** [jisc-content/ukmhl-lab-data#1]
So, how do I get at the images in the set (or a subset) and/or metadata for images in the set (or a subset)? I imagine via the API but it isn't super clear if that is possible.. (as far as my confused mind can tell) cc @ostephens

**Comment by ostephens** [comment]
For the data sets in this repo the 'publications.csv' files contain a column called 'illustrations' which contains URLs for each image in a publication. Additionally each of the 'pages.csv' files contains an illustrations column which has the images per page.

I you want to retrieve via the API then you can look for the 'illustrations' element in the publications json
